import type { AidId, RankingPeriod } from '../content/economy';
export interface AccountSnapshot { balance: number; paymentStatus?:'paid'|'refunded'|'reversed'; attempts?:{day:string;freeRemaining:number;adRemaining:number;adAvailable:number;purchasedRemaining:number;renewsAt:string}; dailyBest?:number; legacyDailyBest?:number; dailyParticipants?:number;
 missionsRenewAt?:string; notifications?:PodiumNotification[]; progress?:{badgeCatalogVersion?:number; badgeClaims?:string[]; achievements:string[];badgeProgress:Record<string,number>;missions:Record<string,{progress:number;claimed:boolean}>;runs:number}; referral?:{code:string;qualified:number;paid:number;paidToday:number;earnedCoins:number}; inventory: Partial<Record<AidId, number>>; onlineCosmetics: string[]; recoverable: boolean; gameplayEarned: number; missionEarned: number; adBonusClaims: number; transactions: { id: string; source: string; coins: number; items: Partial<Record<AidId, number>>; createdAt: string }[]; }
export interface RunTicket { id: string; mode: 'casual' | 'daily'; seed: string; catalog: 'legacy-18' | 'extended-24' | 'extended-30'; ruleset: 'v2' | 'v3'; startedAt: string; expiresAt: string; aids: AidId[]; aidRulesVersion?:1|2; }
export interface ReplayInput { tick: number; action: 'drop' | 'aid'; aid?: AidId; }
export interface ReplaySubmission { runId: string; ruleset?: 'v2'|'v3'; finalTick: number; events: ReplayInput[]; }
export interface AccountRun { id: string; status: 'started' | 'pending' | 'validating' | 'accepted' | 'rejected' | 'verification_timeout'; error?: string; result?: { height: number; score: number; objectsPlaced: number; perfectDrops: number; maxCombo: number; earnedCoins: number; completedMissions?:string[]; newAchievements?:string[]; }; }
export interface RankingEntry { rank: number; name: string; height: number; score: number; points: number; wins: number; aidsUsed: AidId[]; coins: number; items: Partial<Record<AidId, number>>; }
export interface RankingSnapshot { period: RankingPeriod; periodId: string; startUTC: string; endUTC: string; settlesAt: string; status: 'open' | 'settled'; rewardState?:'locked'|'eligible'|'settling'|'paid'|'no-minimum'|'none'; minimumParticipants?:number; participants: number; entries: RankingEntry[]; ownEntry: RankingEntry | null; }

export interface PodiumNotification { id:string; period:RankingPeriod; periodId:string; rank:number; final:boolean; coins:number; minimumMet:boolean; }
