import { getLanguage, t } from '../services/i18n';
export interface LegalSection {title:string;paragraphs:string[];}
export interface LegalDocument {path:string;title:string;description:string;sections:LegalSection[];}
export const LEGAL_VERSION='2026-10-08';
export const LEGAL_OPERATOR={name:'Renzo Dogliotti',address:'Ruta 8, Montevideo, Uruguay',email:'newsolutions.uy@gmail.com'};
export const LEGAL_DOCUMENTS:Record<'privacy'|'terms'|'ranking',LegalDocument>={
privacy:{path:"/privacidad/",title:"Política de privacidad",description:"Cómo usamos tus datos en Impossible Tower.",sections:[
{title:"Responsable y contacto",paragraphs:["Impossible Tower es operado por Renzo Dogliotti, Ruta 8, Montevideo, Uruguay. Consultas y solicitudes sobre datos: newsolutions.uy@gmail.com."]},
{title:"Datos locales y cuentas",paragraphs:["Guardamos en el navegador preferencias, idioma, historial, cosméticos y progreso de práctica. Borrar ese almacenamiento puede perder progreso de invitado. Los invitados usan una identidad anónima para verificar práctica y participar en el mensual. Un nombre público es obligatorio: evitá datos sensibles o de terceros."]},
{title:"Google y Supabase",paragraphs:["Al elegir Google, Google procesa el acceso y Supabase conserva la sesión e identidad. El servidor guarda saldo, inventario, insignias, progreso, tickets y entradas del replay para validar partidas, premios y misiones. Vincular un invitado a una nueva cuenta conserva su progreso; recuperar una cuenta existente carga esa cuenta sin fusionar saldos."]},
{title:"Edad y autorización",paragraphs:["El juego está dirigido a personas desde los 13 años. Las funciones online entre 13 y 17 años requieren autorización de un adulto responsable. Guardamos la franja de edad y autorización declaradas, no la fecha de nacimiento completa. Publicidad y compras requieren 18 años o más."]},
{title:"Publicidad opcional",paragraphs:["Google H5 permanece desactivado hasta verificar el proveedor y la plataforma de consentimiento (CMP). Las elecciones locales por sí solas no habilitan publicidad. No cargamos anuncios para menores, edad desconocida o sin consentimiento válido. Un anuncio completo puede entregar un intento Daily, nunca monedas. Podés retirar el consentimiento desde las preferencias."]},
{title:"Referidos y operaciones",paragraphs:["Si abrís un enlace personal, el servidor conserva la primera atribución válida durante siete días. Registra cuentas calificadas, cuotas, anuncios completados, emisión y gastos para prevenir pagos repetidos y evaluar la economía. El usuario comparte enlaces de forma voluntaria; no enviamos mensajes a sus contactos."]},
{title:"Proveedores y seguridad",paragraphs:["Netlify aloja el juego y puede conservar registros técnicos de solicitudes. Supabase guarda los datos online; Google interviene para acceso y publicidad habilitada. Estos proveedores pueden procesar datos fuera de Uruguay. No vendemos datos personales. Aplicamos controles de acceso y validación del servidor; ningún servicio garantiza ausencia total de fallos."]},
{title:"Conservación y derechos",paragraphs:["Los datos locales permanecen hasta que vos o el navegador los borren. Los datos online se conservan mientras sean necesarios para el servicio, seguridad, reclamos y obligaciones legales. Podés solicitar información, acceso, actualización, rectificación o eliminación por email. Solo pediremos datos necesarios para verificar titularidad. Podés acudir a la URCDP si tus derechos no fueron atendidos."]},
{title:"Compras y cambios",paragraphs:["Cuando las compras estén habilitadas, PayPal procesa el pago. Conservamos identificadores de orden y captura, importe, moneda y estados de entrega o reembolso para conciliar tu saldo. No recibimos los datos completos de tu medio de pago. Publicaremos cambios materiales cuando corresponda."]},
]},
terms:{path:"/terminos/",title:"Términos de uso",description:"Condiciones del juego y de sus monedas virtuales.",sections:[
{title:"Responsable y alcance",paragraphs:["Impossible Tower es operado por Renzo Dogliotti, Ruta 8, Montevideo, Uruguay. Contacto: newsolutions.uy@gmail.com. Los derechos obligatorios de usuarios y consumidores prevalecen sobre estos términos."]},
{title:"Participación",paragraphs:["El juego requiere 13 años o más; las funciones online para menores de 18 requieren autorización de un adulto. Los invitados pueden practicar y competir en el mensual, sin monedas ni Daily competitivo. Google permite conservar saldo y progreso entre dispositivos. Sin conexión podés practicar localmente; esa partida no participa en rankings ni acredita monedas."]},
{title:"Monedas virtuales",paragraphs:["Hay un solo saldo, administrado por el servidor. Las monedas locales de la etapa anterior se resetean sin convertirse a premium; se conserva historial, logros y cosméticos. Las monedas sirven solo dentro del juego, sin transferencia ni canje por dinero, criptomonedas o premios reales."]},
{title:"Fuentes y precios",paragraphs:["Cada cuenta Google nueva recibe 60 monedas una vez. Cinco misiones diarias pagan 2 cada una, máximo 10 al día. Un referido válido paga 5, máximo 10 pagos diarios por invitador. El ranking semanal paga los premios publicados; Plata y Oro tienen premios únicos reclamables. Los códigos promocionales tienen vigencia y cupo. No hay monedas por partida, récord, anuncios ni compartir. Intento adicional: 30 monedas; segunda chance: 90. Cada compra con monedas requiere confirmación."]},
{title:"Anuncios e intentos",paragraphs:["Daily ofrece tres intentos gratuitos por cuenta y día UTC y hasta dos extras por anuncios completos. Comprar intentos no tiene límite diario si alcanza el saldo. Los extras vencen con el día y no se acumulan. Cancelar, no encontrar anuncio o un error no entrega extras. Todos los intentos compiten con el mismo reglamento y secuencia."]},
{title:"Compras y entrega",paragraphs:["Los packs son 200 monedas/USD 2,99; 600/USD 6,99; 1.400/USD 12,99. Solo se pueden comprar cuando el servicio esté habilitado, con una cuenta Google y una persona adulta que confirme la compra. Verás el importe total antes de continuar a PayPal. Las monedas se entregan cuando el servidor confirma la captura; volver del checkout no acredita saldo. Un pago pendiente se concilia con PayPal. Cancelar antes del pago no entrega monedas. Reembolsos y reversiones corrigen el saldo, incluso si las monedas ya se gastaron. Reclamos: newsolutions.uy@gmail.com.","Cuando corresponda por la normativa uruguaya, las contrataciones a distancia tienen un derecho de retracto de cinco días hábiles contado desde la formalización o entrega, a elección del consumidor, en los términos de la Ley N.º 17.250. Las condiciones de uso o ejecución de contenido digital y cualquier excepción aplicable deberán informarse antes de pagar; no establecemos una regla general de compras sin reembolso."]},
{title:"Progreso, cambios e incidencias",paragraphs:["Podemos ajustar precios, física y contenido con reglas económicas versionadas por evento; los ajustes no alteran premios ya prometidos. Un fallo técnico confirmado devuelve el recurso consumido según el registro del servidor. Abandonar, perder o enviar un resultado inválido no lo devuelve. El progreso de invitado puede perderse al cambiar de navegador."]},
{title:"Uso permitido y reclamos",paragraphs:["No manipules resultados, cuentas, referidos ni recompensas; no uses bots para obtener premios ni publiques datos privados de terceros. Podemos excluir resultados ante evidencia de abuso. Consultas, revisión, eliminación de datos y reclamos de pagos: newsolutions.uy@gmail.com. No excluimos garantías ni responsabilidad que una norma obligatoria impida excluir."]},
{title:"Propiedad y legislación",paragraphs:["Podés jugar y compartir enlaces y tarjetas generados por el juego para uso personal. El juego y sus contenidos están protegidos; no se autoriza su reventa. Se aplica la legislación uruguaya sin afectar las normas obligatorias de tu jurisdicción. Informaremos cambios materiales antes de aplicarlos."]},
]},
ranking:{path:"/reglas-ranking/",title:"Reglas de rankings y recompensas",description:"Competencia, intentos, misiones y referidos.",sections:[
{title:"Modos y disponibilidad",paragraphs:["Daily Tower tiene vistas Hoy, Semana e Histórico. Juego libre conserva su ranking mensual. Los premios dependen de la activación del evento online. Los resultados locales no compiten. Los períodos anteriores conservan las reglas guardadas al abrirse; los nuevos premios semanales comienzan un lunes UTC."]},
{title:"Clasificación",paragraphs:["Hoy e Histórico toman la mejor torre Daily por cuenta Google del día o desde V3, respectivamente. Juego libre mensual toma la mejor práctica de Google o invitados, sin sumar Daily. Exigen cinco objetos y replay aceptado. Se ordenan por altura, puntaje, objetos y recepción, con ID interno como último desempate. El semanal suma puntos de los tres mejores días; quien juega menos suma los días disponibles. Los puntos diarios van de 10 a 100 según puesto; un único participante recibe 10. Desempates semanales: victorias de los días contados, mejor altura, recepción más temprana de un resultado contribuyente e ID."]},
{title:"Horarios UTC y validación",paragraphs:["El día cierra a medianoche UTC; la semana, el lunes siguiente a las 00:00 UTC; el mes, el primer día del siguiente mes. Un ticket permite 40 minutos activos y 60 desde su emisión. Enviar antes de vencer y dentro de 60 minutos del cierre diario. La liquidación empieza 75 minutos después del cierre y espera las clasificaciones diarias. Un puesto provisional no garantiza un premio."]},
{title:"Física y ayudas v3",paragraphs:["Se pierde cuando cualquier objeto cae por debajo de la zona de juego. Moverse o balancearse levemente no es caída. Hay hasta dos ayudas distintas por intento; Guía 5 y Guía 10 no se combinan. Una segunda chance con al menos tres objetos restaura el estado previo al último lanzamiento ante caída, cuesta 90 monedas y no consume otro Daily. No recupera partidas terminadas por tiempo."]},
{title:"Elegir ayudas",paragraphs:["Elegí ayudas de tu inventario durante la partida, sin prepararlas. Máximo dos distintas, una vez cada una. Guía 5 y Guía 10 no se combinan y duran los próximos 5 o 10 lanzamientos. Una segunda chance recuperable requiere tres objetos, ocupa un lugar de ayuda y puede comprarse por 90 monedas con confirmación; no recupera timeouts."]},
{title:"Intentos",paragraphs:["Tres gratuitos por cuenta y día, hasta dos por anuncios completos y compras de 30 monedas sin límite si alcanza el saldo. Se consume al emitir el ticket. Extras del mismo día, sin acumulación. Todos usan idéntica secuencia y reglamento. Abandonar o perder no devuelve intentos."]},
{title:"Premios semanales y podios",paragraphs:["El semanal requiere 20 cuentas Google distintas con al menos un Daily aceptado de cinco objetos durante la semana. Paga primero 60; segundo 40; tercero 20; puestos 4–10, 10; puestos 11–25, 4 monedas. Máximo 250 monedas por semana; con 19 o menos no paga. Los nuevos eventos Hoy e Histórico no pagan monedas. Los podios semanales y mensuales avanzan sus insignias al cierre. Cada premio se liquida una sola vez; los períodos anteriores conservan sus reglas."]},
{title:"Misiones",paragraphs:["Cada día UTC: completar tres torres de cinco objetos; acumular ocho Perfect; alcanzar 30 metros; colocar 25 objetos acumulados; completar dos Daily de cinco objetos. Cada misión paga dos monedas una vez, máximo diez. Práctica y Daily aceptados cuentan. Invitados ven progreso sin cobrar; iniciar sesión no acredita misiones anteriores. Una segunda chance conserva el resultado provisional hasta finalizar, contando progreso una sola vez."]},
{title:"Insignias y promociones",paragraphs:["Las insignias tienen Bronce, Plata y Oro. Bronce reconoce la hazaña; Plata y Oro permiten reclamar una vez monedas o ayudas según el catálogo. El catálogo nuevo empieza desde cero, sin borrar saldo, inventario ni récords. Los códigos promocionales requieren Google y admiten un canje por cuenta y campaña, sujeto a vigencia y cupo."]},
{title:"Referidos",paragraphs:["Un enlace personal atribuye la primera invitación válida durante siete días. Una nueva cuenta Google debe completar su primer Daily verificado de al menos cinco objetos. Paga cinco monedas al invitador aunque no haya 20 participantes. Excluye cuentas existentes, autorreferidos y pagos repetidos. Máximo diez pagos por invitador y día: los adicionales no pagan ni quedan pendientes."]},
{title:"Integridad y reclamos",paragraphs:["No están permitidos bots, resultados manipulados o cuentas múltiples para duplicar beneficios o participantes. La validación actual no garantiza ausencia de trampas. Un fallo técnico confirmado puede compensarse una vez según el ledger. Para revisión o reclamos: newsolutions.uy@gmail.com. Las monedas y premios son virtuales, sin transferencia ni canje por dinero."]},
]},
};
const escapeLegal=(text:string)=>text.replace(/[&<>"']/g,value=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[value]!));
export function renderLegalBody(document:LegalDocument,localized=false):string {
 const translate=localized?t:(value:string)=>value;
 return `<p class="legal-notice">${translate('VIGENTE DESDE')} ${LEGAL_VERSION}</p><p class="dialog-description">${escapeLegal(translate(document.description))}</p>${document.sections.map(s=>`<section><h2>${escapeLegal(translate(s.title))}</h2>${s.paragraphs.map(p=>`<p class="legal-copy">${escapeLegal(translate(p))}</p>`).join('')}</section>`).join('')}`;
}
export function renderLegalPage(document:LegalDocument):string {
 return `<!doctype html><html lang="es-UY"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escapeLegal(t(document.description))}"><title>${escapeLegal(t(document.title))} · Impossible Tower</title><style>body{margin:0;background:#f4efdf;color:#172e38;font:17px/1.65 system-ui,sans-serif}main{max-width:760px;padding:40px 24px 64px;margin:auto}nav{display:flex;flex-wrap:wrap;gap:16px;font-size:14px}a{color:inherit}h1{font-size:36px;line-height:1.2}h2{font-size:22px;margin-top:32px}.legal-notice{font-size:12px}footer{margin-top:40px;border-top:1px solid;padding-top:20px}</style></head><body><main><nav><a href="/">${t('Volver al juego')}</a>${Object.values(LEGAL_DOCUMENTS).map(d=>`<a href="${getLanguage()==='en'?'/en':''}${d.path}">${escapeLegal(t(d.title))}</a>`).join('')}</nav><h1>${escapeLegal(t(document.title))}</h1>${renderLegalBody(document,true)}<footer>${LEGAL_OPERATOR.name} · ${LEGAL_OPERATOR.address}<br><a href="mailto:${LEGAL_OPERATOR.email}">${LEGAL_OPERATOR.email}</a></footer></main></body></html>`;
}
