export interface LegalSection {
  title: string;
  paragraphs: string[];
}

export interface LegalDocument {
  path: string;
  title: string;
  description: string;
  sections: LegalSection[];
}

export const LEGAL_VERSION = '2026-10-03';
export const LEGAL_OPERATOR = { name: 'Renzo Dogliotti', address: 'Ruta 8, Montevideo, Uruguay', email: 'newsolutions.uy@gmail.com' };

const prizeDescription = (period: RankingPeriod): string => [1, 2, 3, 4, 11].map((rank, index) => `${['1.º', '2.º', '3.º', 'puestos 4 a 10', 'puestos 11 a 25'][index]}: ${rankingPrize(period, rank, 100).coins} coins`).join('; ');

export const LEGAL_DOCUMENTS: Record<'privacy' | 'terms' | 'ranking', LegalDocument> = {
  privacy: {
    path: '/privacidad/',
    title: 'Política de privacidad',
    description: 'Cómo se usan los datos y cómo ejercer tus derechos en Impossible Tower.',
    sections: [
      { title: 'Responsable y contacto', paragraphs: ['El responsable de Impossible Tower es Renzo Dogliotti, con domicilio en Ruta 8, Montevideo, Uruguay. Consultas y solicitudes sobre datos personales: newsolutions.uy@gmail.com. Esta política se rige por la normativa aplicable, incluida la Ley uruguaya N.º 18.331.'] },
      { title: 'Juego local y datos del dispositivo', paragraphs: ['El juego guarda en el navegador el progreso, coins, cosméticos, misiones, logros, récords, preferencias y el registro de recompensas. También guarda la franja de edad declarada, la declaración de autorización del adulto responsable y la elección sobre publicidad. No pedimos la fecha de nacimiento completa para esta elección.', 'El almacenamiento local permite conservar el juego entre visitas y funcionar offline después de la primera carga. Podés borrarlo desde el navegador; hacerlo puede eliminar el progreso local. Si el almacenamiento no está disponible, las preferencias pueden durar únicamente durante la sesión.'] },
      { title: 'Servicios online opcionales', paragraphs: ['Cuando Supabase esté configurado y habilites las funciones online, se podrá crear una sesión anónima y guardar un identificador de cuenta, el nombre público opcional, resultados, desafíos y una copia privada del perfil. Se usan para rankings, enlaces de desafío y respaldo.', 'Si elegís vincular una cuenta recuperable, se utiliza tu email para enviar un código de acceso, autenticarte y recuperar la cuenta. El email no aparece en los rankings. Se podrá mantener un saldo online separado del progreso y las coins locales; estos no se importan automáticamente al saldo del servidor. Los rankings con premios y las compras siguen sujetos a una activación posterior.', 'Los rankings y desafíos muestran los datos públicos necesarios, como pseudónimo y altura. No uses tu nombre real, email u otros datos privados como pseudónimo. El resto del perfil no se publica en los rankings. Jugar localmente no requiere activar estas funciones.'] },
      { title: 'Edad y autorización', paragraphs: ['El juego está dirigido a personas desde los 13 años. Para personas de 13 a 17 años, las funciones online requieren autorización del padre, madre o tutor. La declaración almacenada en el dispositivo no constituye una verificación de identidad ni sustituye la intervención real del adulto responsable.', 'La publicidad y las futuras compras se limitan a mayores de 18 años en esta versión. No habilitamos anuncios para menores ni para una edad sin declarar. Si detectamos datos de un menor sin la autorización requerida, el adulto responsable puede solicitar su eliminación.'] },
      { title: 'Publicidad y consentimiento', paragraphs: ['Google H5 Games Ads está preparado, pero permanece desactivado hasta contar con aprobación, configuración válida y una plataforma de gestión de consentimiento (CMP) adecuada. No cargamos su script con una edad desconocida, para menores o sin consentimiento publicitario vigente. Las elecciones locales por sí solas no habilitan publicidad.', 'Si se activa, cada anuncio recompensado será opcional y explicará la recompensa antes de aceptarlo. Google y los proveedores autorizados podrán usar almacenamiento, identificadores del dispositivo y datos técnicos según la CMP y sus políticas. Rechazar o retirar el consentimiento permite seguir jugando y bloquea nuevas solicitudes de anuncios. La retirada no revierte tratamientos anteriores lícitos.', 'Las páginas públicas de privacidad, términos y reglas no incorporan scripts de anuncios. La versión actual no incorpora un servicio externo de analítica comercial.'] },
      { title: 'Alojamiento y proveedores', paragraphs: ['Netlify aloja el sitio y puede tratar datos técnicos de las solicitudes, como dirección IP, fecha, navegador y registros de seguridad. Supabase puede tratar los datos online indicados cuando esté configurado. Google intervendrá únicamente si se habilita la publicidad con los requisitos anteriores. No vendemos datos personales.', 'La infraestructura de estos proveedores puede procesar datos fuera de Uruguay. Antes de habilitar funciones que lo requieran, el responsable debe configurar las garantías y condiciones aplicables a estas transferencias. Los proveedores también publican sus políticas en netlify.com/privacy, supabase.com/privacy y policies.google.com/privacy.'] },
      { title: 'Conservación y seguridad', paragraphs: ['Los datos locales permanecen hasta que los borres o el navegador los elimine. Los datos online se conservan mientras sean necesarios para las funciones solicitadas, la seguridad, la atención de reclamos y las obligaciones legales aplicables. Al atender una solicitud de eliminación, podemos conservar únicamente lo exigido por ley o lo necesario para un reclamo pendiente, restringiendo su uso.', 'Aplicamos medidas razonables de seguridad y acceso, pero ningún servicio garantiza ausencia total de fallos. No envíes contraseñas, documentos ni información sensible por un nombre público o enlace de desafío.'] },
      { title: 'Tus derechos', paragraphs: ['Podés solicitar información, acceso, actualización, rectificación, inclusión o supresión de tus datos escribiendo a newsolutions.uy@gmail.com. Indicá la solicitud y el identificador o pseudónimo que permita localizar tus datos; solo pediremos información adicional necesaria para verificar la titularidad. Atenderemos la solicitud dentro de los plazos legales aplicables.', 'Podés retirar el consentimiento publicitario desde las preferencias del juego. Para datos del navegador, también podés usar sus herramientas de almacenamiento. Si considerás que tus derechos no fueron atendidos, podés acudir a la Unidad Reguladora y de Control de Datos Personales de Uruguay (URCDP).'] },
      { title: 'Pagos opcionales y cambios', paragraphs: ['Las compras se habilitan únicamente después de completar la configuración y autorización del proveedor. Si están disponibles, PayPal procesa el pago en su checkout y recibe los datos que solicite para esa operación. El juego conserva el identificador de orden y captura, pack comprado, importe, moneda, estado, fecha y ajustes de devolución para entregar coins, conciliar pagos y atender reclamos; no guarda el número de tarjeta.', 'Los registros de operaciones se conservan durante los plazos que exijan las obligaciones contables, fiscales y la atención de controversias. PayPal publica su política en paypal.com/uy/legalhub/privacy-full. Un pago de prueba o una confirmación solo del navegador no acredita coins online.', 'Publicaremos aquí las modificaciones y su fecha. Un cambio material que requiera una nueva autorización o consentimiento se presentará antes de habilitar el tratamiento correspondiente.'] },
    ],
  },
  terms: {
    path: '/terminos/',
    title: 'Términos de uso',
    description: 'Condiciones para jugar, usar coins y participar en Impossible Tower.',
    sections: [
      { title: 'Responsable y alcance', paragraphs: ['Impossible Tower es operado por Renzo Dogliotti, Ruta 8, Montevideo, Uruguay. Contacto: newsolutions.uy@gmail.com. Estos términos explican las condiciones del juego web distribuido en Netlify. Los derechos obligatorios de usuarios y consumidores prevalecen sobre cualquier disposición de este documento.'] },
      { title: 'Edad y funciones disponibles', paragraphs: ['El juego está dirigido a personas desde los 13 años. Si tenés entre 13 y 17 años, las funciones online requieren la intervención y autorización de tu padre, madre o tutor. Las compras deberán realizarlas personas mayores de 18 años con una cuenta y medio de pago propios o autorizados.', 'El juego local es gratuito. Las cuentas, compras, anuncios y rankings con premios se habilitan por etapas y dependen de una configuración válida. Una función anunciada para una etapa posterior no constituye una oferta activa. Si el juego no muestra un evento o checkout habilitado, no está disponible.'] },
      { title: 'Coins, cosméticos y recompensas', paragraphs: ['Las coins y los objetos virtuales sirven únicamente dentro de Impossible Tower. No representan dinero, depósitos, inversiones ni un saldo financiero. No pueden venderse, transferirse entre jugadores, canjearse por efectivo, premios reales o criptomonedas.', 'Las coins locales se obtienen jugando y con objetivos del juego. La cuenta online, cuando se habilite, tiene su propio saldo y registro de operaciones: no importa automáticamente coins locales. Las recompensas publicitarias locales guardan sus límites en el dispositivo; la cuenta online aplica los límites que muestre el juego. No se exige pagar ni mirar anuncios para jugar o entrar a rankings.'] },
      { title: 'Anuncios opcionales', paragraphs: ['Solo se solicitan anuncios recompensados cuando elegís una recompensa disponible. La cancelación, un error, falta de inventario o la ausencia de confirmación de finalización no concede la recompensa. Las pruebas y simulaciones de anuncios no equivalen a ingresos publicitarios ni a créditos de una futura billetera del servidor.', 'La aprobación y disponibilidad de Google H5 no están garantizadas. La publicidad permanece bloqueada para menores de 18 años y mientras falte una CMP configurada y consentimiento vigente. Rechazar publicidad no impide continuar con el juego gratuito.'] },
      { title: 'Rankings y desafíos', paragraphs: ['Los rankings y desafíos tienen finalidad recreativa. Los resultados publicados dependen de servicios externos disponibles y de las reglas vigentes de cada modalidad. El ranking clásico excluye partidas asistidas; los eventos nuevos de cuenta admiten las ayudas dentro de sus límites publicados. Consultá las reglas públicas antes de participar.', 'Si se habilitan eventos con coins o ayudas virtuales, se aplicarán las fechas UTC, elegibilidad, criterios, premios, límites y forma de entrega publicados. La participación será gratuita y esos premios no serán canjeables por dinero. No existe una promesa de premios mientras el evento no esté habilitado y publicado.'] },
      { title: 'Uso permitido y moderación', paragraphs: ['No manipules resultados, solicitudes de recompensas, identidad de cuentas o registros de pago; no uses automatización para obtener premios ni publiques contenido ilegal, ofensivo o datos privados de terceros. Podremos ocultar nombres, excluir resultados y restringir funciones online ante evidencia de abuso, de forma proporcionada.', 'Podés consultar o impugnar una medida por newsolutions.uy@gmail.com. La revisión no garantiza la validez de un resultado ni sustituye los mecanismos de seguridad. Las comprobaciones actuales no constituyen un sistema anti-cheat completo.'] },
      { title: 'Progreso, disponibilidad y actualizaciones', paragraphs: ['El progreso local puede perderse al borrar datos del navegador, cambiar de dispositivo o por fallos del almacenamiento. El respaldo del perfil no restaura automáticamente todo el progreso local. Cuando esté habilitada, una cuenta vinculada por email permite recuperar su sesión y consultar su saldo online; las coins locales y el saldo online son registros diferentes. Podremos actualizar reglas, precios virtuales, física y contenidos, informando cambios materiales que afecten compras o eventos ya anunciados.', 'El juego y sus servicios externos pueden tener interrupciones. Mantendremos fallbacks para el juego local cuando sea posible. Atenderemos errores y reclamos razonables; estos términos no excluyen responsabilidad ni garantías que una norma obligatoria impida excluir.'] },
      { title: 'Compras y derechos del consumidor', paragraphs: ['Las compras están desactivadas mientras no se muestre un checkout habilitado. Antes de pagar mostraremos cantidad de coins, precio total, moneda, proveedor de cobro, entrega y procedimiento de reclamo. No pediremos datos de tarjeta directamente en el juego ni acreditaremos coins únicamente por volver de un checkout. La entrega online requiere la confirmación del pago por el proveedor y puede quedar pendiente durante su verificación.', 'Cuando corresponda por la normativa uruguaya, las contrataciones a distancia tienen un derecho de retracto de cinco días hábiles contado desde la formalización o entrega, a elección del consumidor, en los términos de la Ley N.º 17.250. Las condiciones de uso o ejecución de contenido digital y cualquier excepción aplicable deberán informarse antes de pagar; no establecemos una regla general de compras sin reembolso.', 'Consultas, pagos duplicados, cargos no autorizados, errores de entrega y solicitudes de devolución: newsolutions.uy@gmail.com. Una devolución o reversión confirmada ajustará las coins correspondientes, incluso si ya fueron gastadas; un saldo virtual negativo puede limitar nuevos canjes hasta compensarse. No genera una deuda de dinero exigible por el juego. Las compras se limitan a mayores de 18 años.'] },
      { title: 'Propiedad intelectual, ley y cambios', paragraphs: ['El juego, su diseño y sus contenidos están protegidos por la legislación aplicable. Podés jugar y compartir los enlaces y tarjetas generados por las funciones del juego para uso personal. Esta autorización no permite revender el juego ni explotar contenidos de terceros sin permiso.', 'Se aplica la legislación uruguaya, sin afectar las normas obligatorias que protejan al usuario en su jurisdicción ni su derecho de acudir a las autoridades competentes. Publicaremos cambios con una nueva fecha y notificaremos los cambios materiales que requieran aceptación antes de aplicarlos.'] },
    ],
  },
  ranking: {
    path: '/reglas-ranking/',
    title: 'Reglas de rankings y recompensas',
    description: 'Reglas actuales y condiciones para futuros eventos de Impossible Tower.',
    sections: [
      { title: 'Disponibilidad de los eventos', paragraphs: ['El juego ofrece récord personal local y, si Supabase está conectado, rankings con resultados reales y desafíos por enlace. No se muestran jugadores ficticios como participantes del ranking.', 'Los rankings de cuenta con coins o ayudas solo están habilitados cuando el juego muestra el evento online correspondiente. Si no se muestra, todavía no están habilitados sus premios. Estas reglas describen los eventos previstos y se aplican al activarlos; su publicación por sí sola no anuncia un evento ni promete un premio.'] },
      { title: 'Participación y edad', paragraphs: ['Participar no requiere pagar, comprar coins ni ver anuncios. Los eventos de cuenta requieren un email verificado. Pueden participar adultos y personas de 13 a 17 años con autorización de su padre, madre o tutor. Una persona no puede usar cuentas múltiples para duplicar premios o simular participantes.', 'El juego local conserva su récord aunque los servicios online no estén disponibles. Los desafíos por enlace y las partidas locales no generan premios de cuenta por sí mismos.'] },
      { title: 'Daily, desafíos y horarios', paragraphs: ['Daily usa la fecha UTC y una secuencia diaria compartida para el catálogo vigente del evento. Los desafíos por enlace reproducen la secuencia mediante un seed; esto no garantiza idéntico rendimiento o física entre dispositivos.', 'El evento diario va de 00:00 UTC a 00:00 UTC del día siguiente. La semana comienza el lunes a 00:00 UTC y termina el lunes siguiente. El mes comienza el día 1 a 00:00 UTC y termina el día 1 del mes siguiente. La zona horaria del dispositivo no cambia el cierre.', 'Una partida online tiene hasta 40 minutos de simulación activa y 60 minutos desde su inicio. Debe enviarse antes de vencer y dentro de los 60 minutos posteriores al cierre diario. El resultado queda pendiente de validación. La clasificación se liquida a partir de 75 minutos después del cierre; ese margen no amplía el plazo de juego.'] },
      { title: 'Clasificación y desempates', paragraphs: ['Cada jugador cuenta con su mejor Daily validado del día, con al menos cinco objetos colocados. Se ordena por altura en centímetros, luego score y cantidad de objetos; después se usa la recepción más temprana del resultado y un identificador interno para resolver cualquier empate restante.', 'El día asigna entre 10 y 100 puntos según la posición: 10 + 90 × (participantes − posición) / (participantes − 1), redondeado al entero más cercano. Si participa una sola persona, recibe 10 puntos. Ganar con al menos dos participantes cuenta como una victoria diaria.', 'La semana suma los mejores cinco días y exige participar en al menos tres días. El mes suma los mejores veinte días y exige al menos diez. Se ordena por puntos, victorias de los días contabilizados y la recepción más temprana del último resultado contabilizado; el identificador interno resuelve un empate restante.'] },
      { title: 'Ayudas admitidas', paragraphs: ['El ranking clásico excluye partidas con segunda oportunidad. Los eventos nuevos de cuenta admiten un máximo de dos ayudas diferentes por torre y muestran las usadas. No pueden combinarse Guía 5 y Guía 10. Se consumen al activarse y solo una vez por tipo en la torre, dentro de las condiciones que muestre el juego.', `Precios de canje actuales: ${Object.values(AID_CATALOG).map(aid => `${aid.name}: ${aid.price} coins`).join('; ')}. Las ayudas se consiguen con coins del juego y con premios de eventos; comprarlas con dinero no es requisito para competir. Duplicar coins no altera altura, score ni clasificación.`, 'Cambiar pieza y segunda oportunidad están admitidos dentro del límite de ayudas del evento. Si un fallo de la infraestructura impide verificar un resultado válido, las ayudas consumidas por esa partida se compensan según el registro del servidor. Un resultado inválido o manipulado no genera compensación.'] },
      { title: 'Premios de coins', paragraphs: ['Con menos de cinco participantes elegibles no se reparten premios. Con cinco a nueve se premia el primer puesto; con diez a veinticuatro, los tres primeros; con veinticinco a noventa y nueve, los diez primeros; desde cien, los veinticinco primeros. Esta regla se aplica por separado al período diario, semanal y mensual.', `Diario: ${prizeDescription('daily')}.`, `Semanal: ${prizeDescription('weekly')}.`, `Mensual: ${prizeDescription('monthly')}.`, 'Los premios son virtuales, personales, no transferibles y sin valor de rescate en dinero. Pueden acumularse los premios de distintos períodos si el jugador resulta elegible en cada uno.'] },
      { title: 'Premios de ayudas y entrega', paragraphs: ['Diario: el primer puesto gana una Guía 5 y el segundo una Vista previa. Semanal: el primero gana una Guía 10 y un Foco; el segundo una Guía 10; el tercero una Guía 5; los puestos cuarto a décimo una Vista previa cada uno.', 'Mensual: el primero gana tres Guía 10 y dos Foco; el segundo dos Guía 10 y un Foco; el tercero una Guía 10; los puestos cuarto a décimo una Guía 5 cada uno. Estas ayudas se entregan únicamente a puestos habilitados por el mínimo de participantes.', 'El cierre y la entrega se validan en servidor y son únicos por jugador y evento. Una posición provisional, un dato del navegador o una prueba de anuncio no garantiza un premio ni permite reclamarlo más de una vez. La liquidación puede demorarse si existe una incidencia técnica; consultá el estado del evento antes de reclamar.'] },
      { title: 'Integridad, incidencias y reclamos', paragraphs: ['No están permitidos resultados manipulados, bots para obtener premios, cuentas coordinadas para duplicar beneficios o reclamos repetidos fraudulentos. El responsable podrá excluir resultados con evidencia de abuso e informar el motivo al atender un reclamo.', 'Las validaciones actuales son básicas y no garantizan ausencia de trampas. Una interrupción puede impedir registrar una partida. Antes de cada evento con premios se publicará el procedimiento para incidencias y revisión. Contacto: newsolutions.uy@gmail.com.'] },
    ],
  },
};

const escapeLegal = (text: string): string => text.replace(/[&<>"']/g, value => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[value]!));

export function renderLegalBody(document: LegalDocument): string {
  return `<p class="legal-notice">VIGENTE DESDE ${LEGAL_VERSION}</p><p class="dialog-description">${escapeLegal(document.description)}</p>${document.sections.map(section => `<section><h2>${escapeLegal(section.title)}</h2>${section.paragraphs.map(paragraph => `<p class="legal-copy">${escapeLegal(paragraph)}</p>`).join('')}</section>`).join('')}`;
}

export function renderLegalPage(document: LegalDocument): string {
  return `<!doctype html><html lang="es-UY"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escapeLegal(document.description)}"><meta name="robots" content="index,follow"><meta name="theme-color" content="#172e38"><title>${escapeLegal(document.title)} · Impossible Tower</title><style>html{color-scheme:light}body{margin:0;background:#f4efdf;color:#172e38;font:17px/1.65 system-ui,sans-serif}main{max-width:760px;padding:40px 24px 64px;margin:auto}nav{display:flex;flex-wrap:wrap;gap:16px;font-size:14px}a{color:inherit;text-underline-offset:4px}h1{font-size:clamp(28px,6vw,42px);line-height:1.2;margin:40px 0 16px}h2{font-size:22px;line-height:1.3;margin-top:32px}.legal-notice{font-size:12px;letter-spacing:.08em}.dialog-description{font-size:19px}footer{margin-top:40px;border-top:1px solid #172e3830;padding-top:20px;font-size:14px}</style></head><body><main><nav aria-label="Navegación legal"><a href="/">Volver al juego</a>${Object.values(LEGAL_DOCUMENTS).map(item => `<a href="${item.path}"${item.path === document.path ? ' aria-current="page"' : ''}>${escapeLegal(item.title)}</a>`).join('')}</nav><h1>${escapeLegal(document.title)}</h1>${renderLegalBody(document)}<footer>${escapeLegal(LEGAL_OPERATOR.name)} · ${escapeLegal(LEGAL_OPERATOR.address)}<br><a href="mailto:${LEGAL_OPERATOR.email}">${LEGAL_OPERATOR.email}</a></footer></main></body></html>`;
}
import { AID_CATALOG, rankingPrize, type RankingPeriod } from './economy';
