import { getLanguage, t } from '../services/i18n';
export interface LegalSection {title:string;paragraphs:string[];}
export interface LegalDocument {path:string;title:string;description:string;sections:LegalSection[];}
export const LEGAL_VERSION='2026-10-07';
export const LEGAL_OPERATOR={name:'Renzo Dogliotti',address:'Ruta 8, Montevideo, Uruguay',email:'newsolutions.uy@gmail.com'};
export const LEGAL_DOCUMENTS:Record<'privacy'|'terms'|'ranking',LegalDocument>={
privacy:{path:"/privacidad/",title:"Política de privacidad",description:"Cómo usamos tus datos en Impossible Tower.",sections:[
{title:"Responsable y contacto",paragraphs:["Impossible Tower es operado por Renzo Dogliotti, Ruta 8, Montevideo, Uruguay. Consultas y solicitudes sobre datos: newsolutions.uy@gmail.com."]},
{title:"Datos locales y cuentas",paragraphs:["Guardamos en el navegador preferencias, idioma, historial, cosméticos y progreso de práctica. Borrar ese almacenamiento puede perder progreso de invitado. Los invitados usan una identidad anónima para verificar práctica y participar en el mensual. Un nombre público es obligatorio: evitá datos sensibles o de terceros."]},
{title:"Google y Supabase",paragraphs:["Al elegir Google, Google procesa el acceso y Supabase conserva la sesión e identidad. El servidor guarda saldo, inventario, insignias, progreso, tickets y entradas del replay para validar partidas, premios y misiones. Vincular un invitado a una nueva cuenta conserva su progreso; recuperar una cuenta existente carga esa cuenta sin fusionar saldos."]},
{title:"Edad y autorización",paragraphs:["El juego está dirigido a personas desde los 13 años. Las funciones online entre 13 y 17 años requieren autorización de un adulto responsable. Guardamos la franja de edad y autorización declaradas, no la fecha de nacimiento completa. Publicidad y futuras compras requieren 18 años o más."]},
{title:"Publicidad opcional",paragraphs:["Google H5 permanece desactivado hasta verificar el proveedor y la plataforma de consentimiento (CMP). Las elecciones locales por sí solas no habilitan publicidad. No cargamos anuncios para menores, edad desconocida o sin consentimiento válido. Un anuncio completo puede entregar un intento Daily, nunca monedas. Podés retirar el consentimiento desde las preferencias."]},
{title:"Referidos y operaciones",paragraphs:["Si abrís un enlace personal, el servidor conserva la primera atribución válida durante siete días. Registra cuentas calificadas, cuotas, anuncios completados, emisión y gastos para prevenir pagos repetidos y evaluar la economía. El usuario comparte enlaces de forma voluntaria; no enviamos mensajes a sus contactos."]},
{title:"Proveedores y seguridad",paragraphs:["Netlify aloja el juego y puede conservar registros técnicos de solicitudes. Supabase guarda los datos online; Google interviene para acceso y publicidad habilitada. Estos proveedores pueden procesar datos fuera de Uruguay. No vendemos datos personales. Aplicamos controles de acceso y validación del servidor; ningún servicio garantiza ausencia total de fallos."]},
{title:"Conservación y derechos",paragraphs:["Los datos locales permanecen hasta que vos o el navegador los borren. Los datos online se conservan mientras sean necesarios para el servicio, seguridad, reclamos y obligaciones legales. Podés solicitar información, acceso, actualización, rectificación o eliminación por email. Solo pediremos datos necesarios para verificar titularidad. Podés acudir a la URCDP si tus derechos no fueron atendidos."]},
{title:"Compras y cambios",paragraphs:["PayPal y sus cobros permanecen deshabilitados. Una entrega posterior deberá publicar condiciones y tratamiento de datos antes de habilitar pagos. Publicaremos cambios materiales y solicitaremos nuevo consentimiento cuando corresponda."]},
]},
terms:{path:"/terminos/",title:"Términos de uso",description:"Condiciones del juego y de sus monedas virtuales.",sections:[
{title:"Responsable y alcance",paragraphs:["Impossible Tower es operado por Renzo Dogliotti, Ruta 8, Montevideo, Uruguay. Contacto: newsolutions.uy@gmail.com. Los derechos obligatorios de usuarios y consumidores prevalecen sobre estos términos."]},
{title:"Participación",paragraphs:["El juego requiere 13 años o más; las funciones online para menores de 18 requieren autorización de un adulto. Los invitados pueden practicar y competir en el mensual, sin monedas ni Daily competitivo. Google permite conservar saldo y progreso entre dispositivos. Sin conexión podés practicar localmente; esa partida no participa en rankings ni acredita monedas."]},
{title:"Monedas virtuales",paragraphs:["Hay un solo saldo, administrado por el servidor. Las monedas locales de la etapa anterior se resetean sin convertirse a premium; se conserva historial, logros y cosméticos. Las monedas sirven solo dentro del juego, sin transferencia ni canje por dinero, criptomonedas o premios reales."]},
{title:"Fuentes y precios",paragraphs:["Cada cuenta Google nueva recibe 60 monedas una vez. Cada misión diaria verificada paga 2, máximo 6 al día. Un referido válido paga 5, máximo 10 pagos diarios por invitador. Daily puede entregar los premios publicados en sus reglas. No hay monedas por partida, récord, insignias, anuncios ni compartir. Intento adicional: 30 monedas; segunda chance: 90. Los precios de otras ayudas se muestran en la tienda."]},
{title:"Anuncios e intentos",paragraphs:["Daily ofrece tres intentos gratuitos por cuenta y día UTC y hasta dos extras por anuncios completos. Comprar intentos no tiene límite diario si alcanza el saldo. Los extras vencen con el día y no se acumulan. Cancelar, no encontrar anuncio o un error no entrega extras. Todos los intentos compiten con el mismo reglamento y secuencia."]},
{title:"Compras deshabilitadas",paragraphs:["Las compras están desactivadas. Packs preparados para el futuro: 200 monedas/USD 2,99; 600/USD 6,99; 1.400/USD 12,99. No hay órdenes ni cobros PayPal en esta versión. Antes de activarlos se publicarán total, entrega, condiciones y reclamos. Las futuras compras requerirán una persona adulta y confirmación del proveedor; volver de un checkout no acredita monedas.","Cuando corresponda por la normativa uruguaya, las contrataciones a distancia tienen un derecho de retracto de cinco días hábiles contado desde la formalización o entrega, a elección del consumidor, en los términos de la Ley N.º 17.250. Las condiciones de uso o ejecución de contenido digital y cualquier excepción aplicable deberán informarse antes de pagar; no establecemos una regla general de compras sin reembolso."]},
{title:"Progreso, cambios e incidencias",paragraphs:["Podemos ajustar precios, física y contenido con reglas económicas versionadas por evento; los ajustes no alteran premios ya prometidos. Un fallo técnico confirmado devuelve el recurso consumido según el registro del servidor. Abandonar, perder o enviar un resultado inválido no lo devuelve. El progreso de invitado puede perderse al cambiar de navegador."]},
{title:"Uso permitido y reclamos",paragraphs:["No manipules resultados, cuentas, referidos ni recompensas; no uses bots para obtener premios ni publiques datos privados de terceros. Podemos excluir resultados ante evidencia de abuso. Consultas, revisión, eliminación de datos y futuros reclamos de pagos: newsolutions.uy@gmail.com. No excluimos garantías ni responsabilidad que una norma obligatoria impida excluir."]},
{title:"Propiedad y legislación",paragraphs:["Podés jugar y compartir enlaces y tarjetas generados por el juego para uso personal. El juego y sus contenidos están protegidos; no se autoriza su reventa. Se aplica la legislación uruguaya sin afectar las normas obligatorias de tu jurisdicción. Informaremos cambios materiales antes de aplicarlos."]},
]},
ranking:{path:"/reglas-ranking/",title:"Reglas de rankings y recompensas",description:"Competencia, intentos, misiones y referidos.",sections:[
{title:"Modos y disponibilidad",paragraphs:["Un panel contiene Daily Tower y Juego libre mensual. Los premios dependen de la activación del evento online; si no se muestra, todavía no están habilitados. Los resultados locales y reglamentos anteriores no entran en la nueva competencia."]},
{title:"Clasificación",paragraphs:["Daily admite cuentas Google y su mejor torre del día. El mensual admite Google e invitados y su mejor práctica del mes; no suma Daily. Una entrada por jugador, con al menos cinco objetos y replay verificado. Se ordena por altura, puntaje, objetos, recepción más temprana e identificador interno para un empate restante. Las ayudas usadas aparecen identificadas."]},
{title:"Horarios UTC y validación",paragraphs:["El día cierra a medianoche UTC; el mes, el primer día del siguiente mes. Un ticket permite 40 minutos activos y 60 desde su emisión. Enviar antes de vencer y dentro de 60 minutos del cierre diario. La liquidación empieza 75 minutos después del cierre, tras validar resultados; la posición provisional no garantiza el premio."]},
{title:"Física y ayudas v3",paragraphs:["Se pierde cuando cualquier objeto cae por debajo de la zona de juego. Moverse o balancearse levemente no es caída. Hay hasta dos ayudas distintas por intento; Guía 5 y Guía 10 no se combinan. Una segunda chance con al menos tres objetos restaura el estado previo al último lanzamiento ante caída, cuesta 90 monedas y no consume otro Daily. No recupera partidas terminadas por tiempo."]},
{title:"Intentos",paragraphs:["Tres gratuitos por cuenta y día, hasta dos por anuncios completos y compras de 30 monedas sin límite si alcanza el saldo. Se consume al emitir el ticket. Extras del mismo día, sin acumulación. Todos usan idéntica secuencia y reglamento. Abandonar o perder no devuelve intentos."]},
{title:"Premios Daily y podio mensual",paragraphs:["Se requieren al menos 20 participantes válidos distintos al cierre. Daily paga monedas: primero 30; segundo 20; tercero 10; puestos 4–10, 5; puestos 11–25, 2. Máximo 125 monedas al día. Con 19 o menos no paga. No entrega ayudas. El podio mensual recibe una insignia permanente, sin monedas. Cada premio se liquida una sola vez según la posición definitiva y las reglas guardadas al abrir el evento."]},
{title:"Misiones",paragraphs:["Cada día UTC: completar tres partidas verificadas de al menos cinco objetos; acumular ocho colocaciones perfectas; alcanzar 30 metros en una partida. Cada una paga dos monedas una vez, máximo seis. Práctica y Daily cuentan. Invitados ven progreso sin cobrar; iniciar sesión no acredita recompensas anteriores. Segunda chance mantiene el resultado provisional hasta finalizar definitivamente, contando progreso una sola vez."]},
{title:"Referidos",paragraphs:["Un enlace personal atribuye la primera invitación válida durante siete días. Una nueva cuenta Google debe completar su primer Daily verificado de al menos cinco objetos. Paga cinco monedas al invitador aunque no haya 20 participantes. Excluye cuentas existentes, autorreferidos y pagos repetidos. Máximo diez pagos por invitador y día: los adicionales no pagan ni quedan pendientes."]},
{title:"Integridad y reclamos",paragraphs:["No están permitidos bots, resultados manipulados o cuentas múltiples para duplicar beneficios o participantes. La validación actual no garantiza ausencia de trampas. Un fallo técnico confirmado puede compensarse una vez según el ledger. Para revisión o reclamos: newsolutions.uy@gmail.com. Las monedas y premios son virtuales, sin transferencia ni canje por dinero."]},
]},
};
const escapeLegal=(text:string)=>text.replace(/[&<>"']/g,value=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[value]!));
export function renderLegalBody(document:LegalDocument,localized=false):string {
 const translate=localized?t:(value:string)=>value;
 return `<p class="legal-notice">${translate('VIGENTE DESDE')} ${LEGAL_VERSION}</p><p class="dialog-description">${escapeLegal(translate(document.description))}</p>${document.sections.map(s=>`<section><h2>${escapeLegal(translate(s.title))}</h2>${s.paragraphs.map(p=>`<p class="legal-copy">${escapeLegal(translate(p))}</p>`).join('')}</section>`).join('')}`;
}
export function renderLegalPage(document:LegalDocument):string {
 return `<!doctype html><html lang="es-UY"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="${escapeLegal(t(document.description))}"><title>${escapeLegal(t(document.title))} · Impossible Tower</title><style>body{margin:0;background:#f4efdf;color:#172e38;font:17px/1.65 system-ui,sans-serif}main{max-width:760px;padding:40px 24px 64px;margin:auto}nav{display:flex;flex-wrap:wrap;gap:16px;font-size:14px}a{color:inherit}h1{font-size:36px;line-height:1.2}h2{font-size:22px;margin-top:32px}.legal-notice{font-size:12px}footer{margin-top:40px;border-top:1px solid;padding-top:20px}</style></head><body><main><nav><a href="/">${t('Volver al juego')}</a><a href="${document.path}">ES</a><a href="/en${document.path}">EN</a>${Object.values(LEGAL_DOCUMENTS).map(d=>`<a href="${getLanguage()==='en'?'/en':''}${d.path}">${escapeLegal(t(d.title))}</a>`).join('')}</nav><h1>${escapeLegal(t(document.title))}</h1>${renderLegalBody(document,true)}<footer>${LEGAL_OPERATOR.name} · ${LEGAL_OPERATOR.address}<br><a href="mailto:${LEGAL_OPERATOR.email}">${LEGAL_OPERATOR.email}</a></footer></main></body></html>`;
}
