import { describe, expect, it, afterEach } from 'vitest';
import Matter from 'matter-js';
import { objectAt, objectForRules } from '../../src/content/objects';
import { TowerSimulation, replayRun } from '../../src/game/simulation/TowerSimulation';
import { nearBadges, recordRun } from '../../src/services/storage/progress';
import { defaultProfile } from '../../src/services/storage/profile';
import { getLanguage, setLanguage, t } from '../../src/services/i18n';
import { encodeChallenge, decodeChallenge } from '../../src/services/sharing/challenge';
const config={mode:'casual' as const,seed:'v3-regression',catalog:'extended-30' as const,ruleset:'v3' as const};
const until=(sim:TowerSimulation,fn:()=>boolean,limit=3000)=>{for(let i=0;i<limit&&!fn();i++)sim.advance(1);expect(fn()).toBe(true);};
const stack=(sim:TowerSimulation,n:number)=>{for(let i=0;i<n;i++){until(sim,()=>sim.state==='ready');until(sim,()=>Math.abs(sim.craneX-210)<.7);expect(sim.drop()).toBe(true);until(sim,()=>sim.stats.objectsPlaced===i+1||sim.state==='over');expect(sim.state).not.toBe('over');}};
afterEach(()=>setLanguage('es'));
describe('v3 gameplay and replay',()=>{
 it('keeps eight opening pieces stable, seeded and immutable while retaining v2',()=>{for(let seed=0;seed<100;seed++)for(let turn=0;turn<8;turn++){const def=objectForRules(String(seed),turn,'extended-30','v3');expect(def.difficultyWeight).toBeLessThanOrEqual(2);expect(def.restitution).toBeLessThanOrEqual(.012);expect(def.friction).toBeGreaterThanOrEqual(.88);expect(objectForRules(String(seed),turn,'extended-30','v3')).toEqual(def);expect(objectForRules(String(seed),turn,'extended-30','v2')).toEqual(objectAt(String(seed),turn,'extended-30'));}});
 it('eight centered pieces support gravity and remain dynamic',()=>{const sim=new TowerSimulation(config);try{stack(sim,8);const bodies=sim.pieces.map(p=>p.body);sim.advance(240);expect(sim.state).toBe('ready');expect(bodies.every(b=>!b.isStatic)).toBe(true);expect(sim.stats.objectsPlaced).toBe(8);}finally{sim.dispose();}});
 it('skipping a piece does not shorten the eight stable opening launches',()=>{const sim=new TowerSimulation(config);try{stack(sim,3);expect(sim.activateAid('skip')).toBe(true);for(let placed=4;placed<=8;placed++){expect(sim.def.difficultyWeight).toBeLessThanOrEqual(2);until(sim,()=>Math.abs(sim.craneX-210)<.7);expect(sim.drop()).toBe(true);until(sim,()=>sim.stats.objectsPlaced===placed||sim.state==='over');expect(sim.state).not.toBe('over');}until(sim,()=>sim.craneX<66);sim.drop();until(sim,()=>sim.state==='over');expect(replayRun(config,sim.events,sim.tick)).toEqual(sim.result);}finally{sim.dispose();}});
 it('an older fallen object ends the run; slight movement does not',()=>{const sim=new TowerSimulation(config);try{stack(sim,3);Matter.Body.translate(sim.pieces[0].body,{x:1,y:0});sim.advance(1);expect(sim.state).toBe('ready');Matter.Body.setPosition(sim.pieces[0].body,{x:210,y:810});sim.advance(1);expect(sim.result?.reason).toBe('collapse');expect(sim.canSecondChance()).toBe(true);}finally{sim.dispose();}});
 it('restores the full state preceding the last drop after an older-piece collapse',()=>{const sim=new TowerSimulation(config);try{stack(sim,3);until(sim,()=>Math.abs(sim.craneX-210)<.7);const before=structuredClone(sim.stats);const poses=sim.pieces.map(p=>({x:p.body.position.x,y:p.body.position.y,angle:p.body.angle,vx:p.body.velocity.x,vy:p.body.velocity.y}));const motion=sim.pieces.map(p=>({motion:p.body.motion,force:{...p.body.force},torque:p.body.torque}));const cursor=sim.sequenceCursor;sim.drop();Matter.Body.setPosition(sim.pieces[0].body,{x:200,y:810});sim.advance(1);expect(sim.activateAid('second-chance')).toBe(true);expect(sim.stats.height).toBe(before.height);expect(sim.stats.objectsPlaced).toBe(before.objectsPlaced);expect(sim.stats.score).toBe(before.score);expect(sim.sequenceCursor).toBe(cursor);expect(sim.pieces).toHaveLength(3);expect(sim.pieces.map(p=>({x:p.body.position.x,y:p.body.position.y,angle:p.body.angle,vx:p.body.velocity.x,vy:p.body.velocity.y}))).toEqual(poses);expect(sim.pieces.map(p=>({motion:p.body.motion,force:{...p.body.force},torque:p.body.torque}))).toEqual(motion);expect(sim.activateAid('second-chance')).toBe(false);}finally{sim.dispose();}});
 it('replays real v3 input identically including a paid continuation',()=>{const sim=new TowerSimulation(config);try{stack(sim,3);until(sim,()=>sim.craneX<66);sim.drop();until(sim,()=>sim.state==='over');expect(sim.activateAid('second-chance')).toBe(true);until(sim,()=>sim.craneX<66);sim.drop();until(sim,()=>sim.state==='over');expect(replayRun(config,sim.events,sim.tick)).toEqual(sim.result);}finally{sim.dispose();}});
 it('continuation cannot revive timeouts or exceed two distinct aids',()=>{const sim=new TowerSimulation(config);try{stack(sim,3);sim.activateAid('focus');sim.activateAid('preview');Matter.Body.setPosition(sim.pieces[0].body,{x:210,y:810});sim.advance(1);expect(sim.canSecondChance()).toBe(false);}finally{sim.dispose();}const timeout=new TowerSimulation(config);try{stack(timeout,3);timeout.advance(144000-timeout.tick);expect(timeout.result?.reason).toBe('timeout');expect(timeout.canSecondChance()).toBe(false);}finally{timeout.dispose();}});
 it('v3 challenge links roundtrip rules and old challenges still decode',()=>{expect(decodeChallenge(encodeChallenge({version:3,catalog:'extended-30',seed:'friends',height:30,score:800}))).toMatchObject({version:3,catalog:'extended-30'});expect(decodeChallenge(encodeChallenge({version:1,seed:'friends',height:30,score:800}))?.version).toBe(1);});
});
describe('v3 progress and languages',()=>{
 it('shows only strictly >90% and <100% pending badges, closest first',()=>{const p=defaultProfile();p.badgeProgress={'fifty-meters':45,'hundred-meters':99,'cloud-toucher':147,'chaos-master':195};expect(nearBadges(p).map(b=>b.id)).toEqual(['hundred-meters','cloud-toucher','chaos-master']);p.badgeProgress['hundred-meters']=100;expect(nearBadges(p).map(b=>b.id)).not.toContain('hundred-meters');});
 it('toggles UI, objects, missions and dynamic sharing copy immediately',()=>{expect(getLanguage()).toBe('es');setLanguage('en');expect(t('JUGAR DE NUEVO')).toBe('PLAY AGAIN');expect(t('Caja feliz')).toBe('Happy box');expect(t('Van 12 de 20 participantes')).toBe('12 of 20 participants');expect(t('Llegué a 30.0 m en Impossible Tower. ¿Me superás?')).toContain('Can you beat me');setLanguage('es');expect(t('JUGAR DE NUEVO')).toBe('JUGAR DE NUEVO');});
});
